### ISSUE TITLE
[Korean] Handle a special present tense conjugation

### ISSUE THREAD

**Issue by yjlim5** [llipio/conjugator#12]
<< Updated>>
If the previous vowel is ㅏ or ㅗ, then add ㄹ and change to 라.  For every other vowel, add ㄹ and change to 러.

This case converts:
1) ㅏ or ㅗ **르** to ㅏㄹ / ㅗㄹ **라** (ex: 모르다 → 몰라) 
2) ㅓ,ㅜ, ㅡ, or ㅣ**르** to ㅓㄹ, ㅜㄹ, ㅡㄹ, ㅣㄹ **러** (ex: 부르다 → 불러요  and 서두르다 → 서둘러요)

**Comment by riceball1** [comment]
I'm trying to deal with this special case, but the combineSymbols function is not producing back the 불 when I get the breakdown array, and push the last symbol it should be [7, 13, 8], but it only returns 부 not 불. @yjlim5 do you think you can check it out? I'm also going to make a pull request, but it will not be finished, it just will have my logic for grabbing out the special present tense case -- but will need to work on dealing with conjugating it.

**Comment by yjlim5** [comment]
I got you @riceball1. thanks for the detailed problem description, i'll take a look and get back to you soon!

**Comment by yjlim5** [comment]
@riceball1, as you suggested, I found the bug in the combineSymbols function.

``` 
    let initialValue = input[0] * 588;
    let medialValue = input[1] * 28; 
    let finalValue = input[3] ? input[3] : 0; 
```

The finalValue's index should be 2, not 3. This should fix the problem you were facing earlier.  Thanks!
