### ISSUE TITLE
Create Past Tense Conjugator for Korean Verbs

### ISSUE THREAD

**Issue by yjlim5** [llipio/conjugator#14]
It seems that the past tense conjugation is the result of present tense conjugation plus ㅆ어. 
ex:  하다 → 해 (present) → 했어 (past)
ex: 오다  → 와 (present) → 왔어 (past) 

let me know if you find any counterexample or if you have any question about the Korean grammar!

**Comment by yjlim5** [comment]
Steps: 
1. call the `doPresent` function on word to get the present tense form.
2. breakdown (present tense word)
3. push ㅆ to the array
4. call the combine function 
5. concatenate '어'

**Comment by heggy231** [comment]
3. Final Jamo: http://www.programminginkorean.com/programming/hangul-in-unicode/composing-syllables-in-unicode/
ex) Final Jamo: ㅆ = 20

**Comment by yjlim5** [comment]
@heggy231 :  just a heads up, there's a bug in the existing korean.js file, line 114.  

Please change `let finalValue = input[3] ? input[3] : 0;` to `let finalValue = input[2] ? input[2] : 0;`, before using the combineSymbols function.

**Comment by thisisrai** [comment]
Does the open pull request solve this issue? Or should continue to work on this? @yjlim5 @minsooshin

**Comment by minsooshin** [comment]
@thisisrai which issue? general past tense functionality or specifically line #114? For general past tense functionality, the PR I have is the one.

**Comment by thisisrai** [comment]
@minsooshin The general past tense functionality. Can we use the `doPresent` function to refactor the code?

**Comment by minsooshin** [comment]
@thisisrai I made a comment on my pull request that I am using `doPresent`. Other than change on `doPast` method, those are fixing existing error in `doPresent`
