### ISSUE TITLE
Korean formality

### ISSUE THREAD

**Issue by songz** [llipio/conjugator#34]
conjugate should take in an options object with formal true/false. This will determine if 요 should be added to the end of the conjugation, or if 야 should be 애요

**Comment by minsooshin** [comment]
correction, `애요` -> `에요`

e.g. 아니야: 아니요, 아니에요

**Comment by cecilebertin** [comment]
Should we not also add the honorific form?

**Comment by minsooshin** [comment]
so `~에요` is one of honorific form.

e.g.
`아니다` and `아니야` are the low forms. `아니에요` and `아닙니다` are honorific forms
BTW, both has same meaning. `아닙니다` sounds more formal like in presentation, speech. `아니에요` is used more in situation like conversation with senior or colleague.

**Comment by songz** [comment]
for this to work, I'd recommend picking a simple rule that works 90% of the time. In this case, I think adding a "요" for past, present, then "에요" for future will suffice. IE:

```
conjugate('가다', {tense: 'past', tone: 'honorific'}) // 갔어요 - what we currently have + 요
conjugate('가다', {tense: 'future', tone: 'honorific'}) // 갔어에요 - what we currently have + 에요
