### ISSUE TITLE
Korean future tense format

### ISSUE THREAD

**Issue by minsooshin** [llipio/conjugator#41]
Current Korean future tense format is `~꺼야`. However, the correct format is ` 거야`
e.f. `가다` -> `갈 거야`, `먹다` -> `먹을 거야`

**Comment by cecilebertin** [comment]
@minsooshin is right I think.
http://www.koreanwikiproject.com/wiki/A/V_%2B_(으)ㄹ_거예요
I added a commit to fix this in my pull request.
