### ISSUE TITLE
[Korean] add irregular verb case for present tense ㅏㄷ,ㄴㅈ,ㅅ/ㅗㄷ,ㄴㅈ,ㅅ

### ISSUE THREAD

**Issue by yjlim5** [llipio/conjugator#47]
ㅏㄷ,ㄴㅈ,ㅅ/ㅗㄷ,ㄴㅈ,ㅅ → followed by 아
앉다 → 앉아요
솟다 → 솟아요
닫다 → 닫아요

please uncomment the tests when working on this issue

**Comment by minsooshin** [comment]
I think this is similar to ㅏㄹ, ㅓㄹ case.
ㅏㄷ, ㅏㄴㅈ, ㅗㅅ -> followed by 아, and ㅓㄷ, ㅓㄴㅈ, ㅜㅅ -> followed by 어

**Comment by cecilebertin** [comment]
I assigned this issue to myself, untill I can assign it to @thisisrai.
